<a href="https://colab.research.google.com/github/sergioGarcia91/Introductorio-Python-3/blob/main/Python_02a_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Python 02a: NumPy

> *Ser tan rápidos como el más lento,\
y ser tan lentos como el más rápido.*

**Autor:** Sergio Andrés García Arias  
**Versión 01:** Diciembre 2023

# Introducción

Hasta ahora, no se ha mencionado la posibilidad de realizar operaciones aritméticas con algunos de los elementos vistos previamente, como la multiplicación de un número con un texto. Aunque este tipo de operaciones son posibles, se debe tener en cuenta que ciertas operaciones no tener un significado claro, lo que pueden llevar a generar resultados inesperados.

Por otro lado, vamos a conocer una nueva estructura de datos poderosa: los `arrays`. Estos nos recuerdan a los `vectores` y `matrices` cotidianas, que en los lenguajes de programación permiten manejar conjuntos de datos de manera más eficiente.

Para utilizar arrays en Python, se requiere el uso de bibliotecas o paquetes específicos implementados por desarrolladores y la comunidad. Un ejemplo destacado es `NumPy`, una biblioteca especializada en el cálculo numérico y el análisis de datos.



---
En este punto, vamos ha hacer un parentesis o pausa para destacar una actividad frecuente y valiosa en el proceso de escritura de código: el uso del buscador en internet. A medida que se enfrenten a desafíos o deseas profundizar en el conocimiento sobre una biblioteca o problema específico, la capacidad de buscar información es esencial.

El buscador sigue siendo una herramienta valiosa para hacer consultas ante inconvenientes o para obtener más información sobre una librería específica. Aunque las IAs pueden ser de gran ayuda en la escritura de código, algunas tareas pueden requerir el apoyo de búsquedas en internet, ya sea en foros de la comunidad o en la documentación oficial de una librería.

Al realizar búsquedas en Internet para obtener información o resolver problemas relacionados con el desarrollo de código, se recomienda preferiblemente utilizar el idioma inglés. La comunidad de programadores en inglés es significativamente más extensa, lo que significa que es más probable encontrar respuestas, soluciones y recursos en este idioma.

---



Al realizar una búsqueda sobre los `arrays` de `NumPy`, es importante especificar que la consulta está orientada a `Python 3`. Aunque no hemos mencionado las diferencias entre versiones de Python, el indicar que la búsqueda es para Python 3, asegura obtener información relevante y actualizada para la versión más reciente del lenguaje. Esto es especialmente relevante dado que Python 2 ha llegado al final de su vida útil, y la comunidad se centra en el desarrollo y soporte de Python 3.

<center><img src='https://github.com/sergioGarcia91/Introductorio-Python-3/blob/main/imagen_BusquedaNumpyArray.png?raw=true' width=500 /></center>

En una consulta rapida en Internet, se puede ver diferentes resultados, entre los que se destacan uno directamente de la pagina de `NumPy`. Es redomendado revisar la [página oficial de NumPy](https://numpy.org) o dirigirse directamente a su [documentación](https://numpy.org/doc/stable/). En nuestra búsqueda de ejemplo, hemos encontrado información valiosa en la sección de [Array Creation](https://numpy.org/doc/stable/user/basics.creation.html) de la documentación oficial.




#Inicio

Recordando de manera simple, aquí está la representación visual de un vector y una matriz:

- Vector

Un vector $V_{m\times 1}$ puede ser representado como:

$$\begin{equation}  
V =
\begin{pmatrix}
v_{11} \\
v_{21} \\
\vdots \\
v_{m1}
\end{pmatrix}
\end{equation}$$

O de manera más compacta:

$$\begin{equation}  
V =
\begin{pmatrix}
v_{1} & v_{2} & \cdots & v_{m}
\end{pmatrix}
\end{equation}$$

- Matriz

Una matriz $A_{n\times m}$ tiene la siguiente forma:

$$ \begin{equation}  
A =
\begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1m}\\
a_{21} & a_{22} & \cdots & a_{2m}\\
\vdots & \vdots & \ddots & \vdots\\
a_{n1} & a_{n2} & \cdots & a_{nm}
\end{pmatrix}
\end{equation}$$

Estos ejemplos no buscan resaltar la complejidad de las matrices ni todas las operaciones que se pueden realizar con ellas, sino simplemente recordar visualmente cómo se representan.

---
Al observar la estructura de un vector, notamos que su representación nos recuerda a una lista en Python.

```python
lista_V = [v1, v2, v3, ... , vm]
```
Al extender la idea de vectores a matrices, una matriz $A$, puede representarse fácilmente como una lista de listas en Python.

```python
lista_de_listas_A = [
  [a11, a12, a13, ... , v1m],
  [a21, a22, a23, ... , v1m],
  [..., ..., ..., ... , ...],
  [an1, an2, an3, ... , vnm],  
]

```
Teniendo en cuenta estas simples observaciones, que podrían tener interpretaciones más detalladas o explicaciones más complejas, optemos por mantenerlas simples por ahora. Procedamos a crear esas dos variables: el vector `lista_V`y la matriz `lista_de_listas_A`.

Como observación adicional, es importante destacar que mientras una lista en Python puede contener múltiples tipos de datos, lo mismo ocurre con los arrays. Sin embargo, por simplicidad, mantendremos la idea de que todos los elementos en nuestras variables serán de tipo numérico.

In [ ]:
# Creamos nuestra lista referente al vector V
lista_V = [1, 2, 3, 4, 5]
print(lista_V)

[1, 2, 3, 4, 5]


In [ ]:
# creamis nuestra lsita de listas referente a la matriz A
lista_de_listas_A = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print(lista_de_listas_A)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


parece que nuestra variable `lista_V` se asemeja a un vector. Sin embargo, en el caso de `lista_de_listas_A`, la estructura de matriz aún no está presente. Esto se debe a que solo creamos listas hasta ahora; aún no las hemos convertido en arrays.

Para solucionar esto, importaremos la biblioteca `NumPy`, que nos permitirá trabajar con arrays de manera eficiente en Python.

```python
import numpy as np
```

In [ ]:
# importamos/llamamos la librería numpy
# el as sirve para establecer un alias o nombre más corto
# sin el alias tendríamos que escribir siempre el nombre completo de la librería numpy
# ahora solo con escribir np ya la maquina va a entender

import numpy as np


Es una buena práctica importar todas las bibliotecas/librerías necesarias al comienzo del Notebook. Esto proporciona claridad y orden en el código. Por la actividad a desarrollar en este Notebook, por esta vez hemos procedido primero con la creación de listas y luego con la importación de NumPy.

Es recomendable seguir el enfoque de importar bibliotecas al inicio del código. Este orden es estándar en la programación y contribuye a un código más legible y estructurado.

---
Para crear un array en NumPy, utilizamos la función `numpy.array()`. Esta función toma una secuencia (como una lista o tupla) y la convierte en un array de NumPy. Para más información puede consultar la [documentación correspondiente](https://numpy.org/doc/stable/reference/generated/numpy.array.html).


In [ ]:
np.array(lista_V)

array([1, 2, 3, 4, 5])

In [ ]:
np.array(lista_de_listas_A)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

ahora cada lista ha sido convertida a un array, y podemos apreciar el cambio en su estructura visual en las salidas de las celdas. Sin embargo, es importante destacar que estos cambios aún no se han guardado en variables específicas.

Para conservar las nuevas estructuras de arrays, debemos asignarlas a nuevas variables. También podemos optar por sobrescribir o reutilizar variables existentes según sea necesario.

En este caso, utilizaremos las variables `vector_V` y `matriz_A` para seguir mas facil el flujo de trabajo.

In [ ]:
vector_V = np.array(lista_V)
matriz_A = np.array(lista_de_listas_A)

print('V= \n', vector_V)
print('A= \n', matriz_A)

V= 
 [1 2 3 4 5]
A= 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Al ejecutar esta celda de código, se obtiene una advertencia de NumPy
# indicando que las listas en lista_2 difieren en longitud.
# Esto se debe a que la primera lista tiene 3 elementos y la segunda tiene 2.
# Aunque NumPy permite la creación de arrays no simétricos
# (en este caso una de las filas es mas corta que la otra),
# es importante tener en cuenta esta advertencia y comprender
# que esto puede afectar las operaciones subsiguientes.

lista_2 = [[1, 2, 3], [4,5]]
array_2 = np.array(lista_2)
print(array_2)

# se recomienda que todos los elementos de los arrays,
# en este caso las filas, tengan el mismo número de
# elementos o columnas

[list([1, 2, 3]) list([4, 5])]


<ipython-input-14-12605b5a9b67>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array_2 = np.array(lista_2)


#Indexing y Slicing

La indexación y el slicing en NumPy es similar a lo visto en las listas, pero a menudo más intuitivas. Se utiliza la notación `[]` después de nuestro array, especificando la fila y la columna de manera numérica `[fila, columna]`. Además, se pueden utilizar los parámetros `inicio:fin:paso` para las filas y las columnas.


In [ ]:
# Para acceder al elemento en la posición 0
print(vector_V[0])  # Salida: 1

# Obtener los elementos desde la posición 0 hasta la 2, recuerde que no se toma el final
print(vector_V[0:3])  # Salida: [1, 2, 3]

# Obtener elementos desde la posición 0 hasta el final, cada 2 pasos
print(vector_V[0::2])  # Salida: [1, 3, 5]

1
[1 2 3]
[1 3 5]


In [ ]:
matriz_A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Con nuestra matriz se puede especificar la fila y la columna
# Si queremos recuperar la fila 1
print(matriz_A[0], '\n') # Salida [1, 2, 3]

# Si se solo la fila 2 y 3 ... recuerde que el ultimo no se toma, por eso se va hasta 3
print(matriz_A[1:3], '\n') # Salida [ [4, 5, 6], [7, 8, 9] ]

# Si queremos recuperar la columna 2, si se debe hacer uso de [fila, columna]
print(matriz_A[:, 1], '\n') # Salida [2, 5, 8]
# En fila se colocó solo : , esto indica en Python TODO

# Para obtener la comunla 2 y 3
print(matriz_A[:, 1:3], '\n') # Salida [ [2, 3], [5, 6], [8, 9]

# Si se quiere los elementos en la columna 2 y 3, pero de las filas 1 y 3
print(matriz_A[::2, 1:3], '\n')  # Salida [ [2, 3], [8, 9]


[1 2 3] 

[[4 5 6]
 [7 8 9]] 

[2 5 8] 

[[2 3]
 [5 6]
 [8 9]] 

[[2 3]
 [8 9]] 



Vamos a crear una matriz más compleja replicando nuestra matriz original, `matriz_A`, en una lista de listas, y multiplicaremos cada una de estas filas por un número diferente. Más adelante, abordaremos en detalle estas operaciones.

In [ ]:

matriz_compleja = [
    [matriz_A, matriz_A*2, matriz_A*3],
    [matriz_A*4, matriz_A*5, matriz_A*6],
     [matriz_A*7, matriz_A*8, matriz_A*9]
    ]

matriz_compleja = np.array(matriz_compleja)
print(matriz_compleja)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[ 2  4  6]
   [ 8 10 12]
   [14 16 18]]

  [[ 3  6  9]
   [12 15 18]
   [21 24 27]]]


 [[[ 4  8 12]
   [16 20 24]
   [28 32 36]]

  [[ 5 10 15]
   [20 25 30]
   [35 40 45]]

  [[ 6 12 18]
   [24 30 36]
   [42 48 54]]]


 [[[ 7 14 21]
   [28 35 42]
   [49 56 63]]

  [[ 8 16 24]
   [32 40 48]
   [56 64 72]]

  [[ 9 18 27]
   [36 45 54]
   [63 72 81]]]]


Vamos a tratar de entenderla:
```python
[
  [matriz_A, matriz_A*2, matriz_A*3], # fila 1 posicicon 0
# col1 pos0  col2 pos1   col3 pos2

  [matriz_A*4, matriz_A*5, matriz_A*6], # fila 2 poscicion 1
# col1 pos0  col2 pos1   col3 pos2

  [matriz_A*7, matriz_A*8, matriz_A*9] #fila 3 posicicon 2
# col1 pos0  col2 pos1   col3 pos2  
]
```

In [ ]:
# para recuperar la primer fila
print(matriz_compleja[0]) # Salida [matriz_A, matriz_A*2, matriz_A*3]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[ 3  6  9]
  [12 15 18]
  [21 24 27]]]


In [ ]:
# para recuperar la tercer fila
print(matriz_compleja[2]) # Salida [matriz_A*7, matriz_A*8, matriz_A*9]

[[[ 7 14 21]
  [28 35 42]
  [49 56 63]]

 [[ 8 16 24]
  [32 40 48]
  [56 64 72]]

 [[ 9 18 27]
  [36 45 54]
  [63 72 81]]]


In [ ]:
# para recuperar
# [matriz_A, matriz_A*3]
# [matriz_A*7, matriz_A*9]

print(matriz_compleja[::2, ::2])

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[ 3  6  9]
   [12 15 18]
   [21 24 27]]]


 [[[ 7 14 21]
   [28 35 42]
   [49 56 63]]

  [[ 9 18 27]
   [36 45 54]
   [63 72 81]]]]


In [ ]:
# para recuperar el [ 3  6  9]

print(matriz_compleja[0, 2, 0])
# o
print(matriz_compleja[0, 2][0])

[3 6 9]
[3 6 9]


In [ ]:
# para recuperar
# [ 3  6  9]
# [12 15 18]
print(matriz_compleja[0, 2, 0:2])
# o
print(matriz_compleja[0, 2][0:2])

[[ 3  6  9]
 [12 15 18]]
[[ 3  6  9]
 [12 15 18]]


In [ ]:
# para recuperar [3, 12]

print(matriz_compleja[0, 2, 0:2, 0])
# o
print(matriz_compleja[0, 2][0:2, 0])

[ 3 12]
[ 3 12]


# Mascara - Filtro

Una `máscara` o `filtro` en NumPy es un tipo de array/vector/matriz que contiene únicamente valores booleanos. Su función principal es indexar otra matriz, debiendo tener la misma forma, para seleccionar elementos específicos a partir de una condición predefinida.

Ejemplo::
```python
# Matriz de interés a filtrar
matriz = np.array([[5.1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Se crea la máscara o filtro a partir de una condición
mascara = matriz > 5
# Condición: solo valores mayores a 5

# Aplicar la máscara a la matriz original
# es tan sencillo como utilizarla como índice
matriz_filtrada = matriz[mascara]

print(matriz_filtrada)
```


In [ ]:
# Matriz de interés a filtrar
matriz = np.array([[5.1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Se crea la máscara o filtro a partir de una condición
mascara = matriz > 5
# Condición: solo valores mayores a 5

# Aplicar la máscara a la matriz original
# es tan sencillo como utilizarla como índice
matriz_filtrada = matriz[mascara]

print('Matriz original: \n', matriz)
print('\n Elementos >5:')
print(matriz_filtrada)

Matriz original: 
 [[5.1 2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]

 Elementos >5:
[5.1 6.  7.  8.  9. ]


---
Lo que acabamos de crear es una representación simple de una matriz con matrices, y podría asociarse con un aumento en las dimensiones. Manejar las dimensiones en los arrays puede parecer complicado al principio, pero para esta serie de Notebooks, nuestros arrays estarán limitados a solo 2 dimensiones, es decir, en una matriz convencional.

#Fin